name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs pipeline on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Uses latest Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls repository files

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specifies Node.js version
          cache: 'npm'  # Caches node_modules for faster builds

      - name: Install Dependencies
        run: |
          npm ci  # Ensures clean and reliable dependency installation

      - name: Run Tests (Optional)
        run: |
          echo "Running tests..."
          # Uncomment the line below if you have tests
          # npm test

      - name: Deploy Code (Placeholder)
        run: echo "Deploying project..."
        # Add actual deployment commands here (FTP, SSH, or CI/CD service)
